# Generated by Django 3.2 on 2024-01-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20240120_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='energy_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=255),
        ),
    ]
