# Generated by Django 3.2.4 on 2024-02-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_construction_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='url',
        ),
    ]
