# Generated by Django 3.2.4 on 2024-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20240411_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenitiesBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_water_heating', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('storage_room', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('attic', models.BooleanField(default=False)),
                ('veranda', models.BooleanField(default=False)),
                ('terrace', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('renovated', models.BooleanField(default=False)),
                ('corner', models.BooleanField(default=False)),
                ('penthouse', models.BooleanField(default=False)),
                ('bright', models.BooleanField(default=False)),
                ('painted', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('satellite', models.BooleanField(default=False)),
                ('internal_stairs', models.BooleanField(default=False)),
                ('double_glass', models.BooleanField(default=False)),
                ('awnings', models.BooleanField(default=False)),
                ('screens', models.BooleanField(default=False)),
                ('bbq', models.BooleanField(default=False)),
                ('solar_heating', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('playroom', models.BooleanField(default=False)),
                ('secure_door', models.BooleanField(default=False)),
                ('security_alarm', models.BooleanField(default=False)),
                ('security_door', models.BooleanField(default=False)),
                ('CCTV', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('basement', models.BooleanField(default=False)),
                ('no_shared_expenses', models.BooleanField(default=False)),
                ('investment', models.BooleanField(default=False)),
                ('student_apartment', models.BooleanField(default=False)),
                ('luxurious', models.BooleanField(default=False)),
                ('for_office_use', models.BooleanField(default=False)),
                ('for_commercial_use', models.BooleanField(default=False)),
                ('for_residential_use', models.BooleanField(default=False)),
                ('for_tourist_use', models.BooleanField(default=False)),
                ('for_warehouse_use', models.BooleanField(default=False)),
                ('for_industrial_use', models.BooleanField(default=False)),
                ('for_agricultural_use', models.BooleanField(default=False)),
                ('distance_from_sea', models.BooleanField(default=False)),
                ('distance_from_city', models.BooleanField(default=False)),
                ('distance_from_airport', models.BooleanField(default=False)),
                ('distance_from_village', models.BooleanField(default=False)),
                ('distance_from_port', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Amenities building',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities_building',
            field=models.ManyToManyField(to='listings.amenitiesBuilding'),
        ),
    ]
