# Generated by Django 3.2.4 on 2024-04-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20240430_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitiesbuilding',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
