# Generated by Django 3.2.4 on 2024-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_amenitiesbuilding_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='amenitiesBuilding',
            new_name='amenities',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='amenities_building',
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(to='listings.amenities'),
        ),
    ]
