# Generated by Django 4.2.7 on 2024-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='alarm',
            new_name='access_for_disabled',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='distance_from_airport',
            new_name='currently_rented',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='distance_from_city',
            new_name='elevator_in_building',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='distance_from_port',
            new_name='ev_charger',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='distance_from_sea',
            new_name='insect_screen',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='distance_from_village',
            new_name='landmark_building',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='for_agricultural_use',
            new_name='loft',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='for_commercial_use',
            new_name='need_renovation',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='for_industrial_use',
            new_name='night_electricity',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='for_office_use',
            new_name='part_complete',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='for_residential_use',
            new_name='suitable_for_agricultural_use',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='for_tourist_use',
            new_name='suitable_for_commercial_use',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='for_warehouse_use',
            new_name='suitable_for_development',
        ),
        migrations.AddField(
            model_name='amenities',
            name='suitable_for_industrial_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='suitable_for_office_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='suitable_for_residential_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='suitable_for_tourist_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='suitable_for_warehouse_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='under_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='underfloor_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='distance_from_airport',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='distance_from_city',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='distance_from_port',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='distance_from_sea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='distance_from_village',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='opening_frames',
            field=models.CharField(choices=[('aluminiun', 'Aluminiun'), ('wooden', 'Wooden'), ('iron', 'Iron'), ('PVC', 'PVC')], default='aluminiun', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='renovation_year',
            field=models.IntegerField(choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024),
        ),
        migrations.AddField(
            model_name='listing',
            name='type_of_glass',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quadruple', 'Quadruple')], default='single', max_length=255),
        ),
    ]
