# Generated by Django 4.2.7 on 2024-05-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_rename_alarm_amenities_access_for_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='orientation',
            field=models.CharField(choices=[('north', 'North'), ('north_east', 'North East'), ('east', 'East'), ('south_east', 'South East'), ('south', 'South'), ('south_west', 'South West'), ('west', 'West'), ('north_west', 'North West')], default='north', max_length=255),
        ),
    ]
