# Generated by Django 4.2.7 on 2024-05-28 16:33

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_orientation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='elevator',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='secure_door',
            new_name='consierge',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='suitable_for_tourist_use',
            new_name='facade',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='surface',
            new_name='floor_area',
        ),
        migrations.AddField(
            model_name='amenities',
            name='inside_the_settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='inside_zone_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='part_funished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='property_consideration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='suitable_for_short_stay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='building_coefficient',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='cover_coefficient',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_type',
            field=models.CharField(choices=[('marble', 'Marble'), ('tile', 'Tile'), ('wooden', 'Wooden'), ('granite', 'Granite'), ('mosaic', 'Mosaic'), ('stone', 'Stone'), ('laminate', 'Laminate'), ('parquet', 'Parquet'), ('carpet', 'Carpet'), ('cement', 'Cement'), ('other', 'Other')], default='marble', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='land_area',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AddField(
            model_name='listing',
            name='length_of_facade',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_charge',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AddField(
            model_name='listing',
            name='wc',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AddField(
            model_name='listing',
            name='zone',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural'), ('tourist', 'Tourist'), ('mixed', 'Mixed'), ('redevelopment', 'Redevelopment'), ('other', 'Other')], default='residential', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_airport',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_city',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_port',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_sea',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_village',
            field=models.IntegerField(default=0, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='energy_class',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('to_be_issued', 'To be issued')], default='A', max_length=255),
        ),
    ]
