# Generated by Django 4.2.7 on 2024-05-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_municipality_listing_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='county',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sub_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('warehouse', 'Warehouse'), ('hotel', 'Hotel'), ('other', 'Other')], default='apartment', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('residential', 'Residential'), ('land', 'Land'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='residential', max_length=255),
        ),
    ]
