# Generated by Django 4.2.7 on 2024-05-30 09:50

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_listing_floor_area_alter_listing_land_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sub_type_commercial',
            field=models.CharField(choices=[('office', 'Office'), ('retail', 'Retail'), ('warehouse', 'Warehouse'), ('mixed_use', 'Mixed Use'), ('industrial', 'Industrial'), ('other', 'Other')], default='office', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='levels',
            field=models.IntegerField(blank=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sub_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('hotel', 'Hotel'), ('other', 'Other')], default='apartment', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('residential', 'Residential'), ('land', 'Land'), ('commercial', 'Commercial')], default='residential', max_length=255),
        ),
    ]
