# Generated by Django 4.2.7 on 2024-05-31 11:17

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listing_sub_type_commercial_alter_listing_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AddField(
            model_name='listing',
            name='storage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address_number',
            field=models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='listings.amenities'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='availability',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='building_coefficient',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='construction_year',
            field=models.IntegerField(blank=True, choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cover_coefficient',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, default='€', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_airport',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_city',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_port',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_sea',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_from_village',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('to_be_issued', 'To be issued')], default='A', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor_area',
            field=models.FloatField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor_type',
            field=models.CharField(blank=True, choices=[('marble', 'Marble'), ('tile', 'Tile'), ('wooden', 'Wooden'), ('granite', 'Granite'), ('mosaic', 'Mosaic'), ('stone', 'Stone'), ('laminate', 'Laminate'), ('parquet', 'Parquet'), ('carpet', 'Carpet'), ('cement', 'Cement'), ('other', 'Other')], default='marble', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='heating_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='kitchens',
            field=models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='land_area',
            field=models.FloatField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='length_of_facade',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='levels',
            field=models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='living_rooms',
            field=models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='opening_frames',
            field=models.CharField(blank=True, choices=[('aluminiun', 'Aluminiun'), ('wooden', 'Wooden'), ('iron', 'Iron'), ('PVC', 'PVC')], default='aluminium', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('north_east', 'North East'), ('east', 'East'), ('south_east', 'South East'), ('south', 'South'), ('south_west', 'South West'), ('west', 'West'), ('north_west', 'North West')], default='north', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='postcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='renovation_year',
            field=models.IntegerField(blank=True, choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='service_charge',
            field=models.FloatField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('hotel', 'Hotel'), ('other', 'Other')], default='apartment', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sub_type_commercial',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('retail', 'Retail'), ('warehouse', 'Warehouse'), ('mixed_use', 'Mixed Use'), ('industrial', 'Industrial'), ('other', 'Other')], default='office', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('land', 'Land'), ('commercial', 'Commercial')], default='residential', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type_of_glass',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quadruple', 'Quadruple')], default='single', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='wc',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zone',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural'), ('tourist', 'Tourist'), ('mixed', 'Mixed'), ('redevelopment', 'Redevelopment'), ('other', 'Other')], default='residential', max_length=255),
        ),
    ]
