# Generated by Django 4.2.7 on 2024-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_amenities_rented_amenities_sold_listing_power_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sub_type_commercial',
        ),
        migrations.AlterField(
            model_name='listing',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('hotel', 'Hotel'), ('office', 'Office'), ('retail', 'Retail'), ('warehouse', 'Warehouse'), ('mixed_use', 'Mixed Use'), ('industrial', 'Industrial'), ('other', 'Other')], default='apartment', max_length=255),
        ),
    ]
