# Generated by Django 4.2.7 on 2024-06-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_remove_listing_sub_type_commercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='amenities',
        ),
        migrations.AddField(
            model_name='amenities',
            name='listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='listings.listing'),
            preserve_default=False,
        ),
    ]
