# Generated by Django 4.2.7 on 2024-06-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_remove_amenities_name_remove_listing_amenities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='agent_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='storage',
        ),
    ]
