# Generated by Django 4.2.7 on 2024-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_remove_listing_city_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address_street_gr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='county_gr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_gr',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='listing',
            name='heating_system_gr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='municipality_gr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_type_gr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='region_gr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
