# Generated by Django 4.2.7 on 2024-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_listing_view_alter_listing_opening_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slope',
            field=models.CharField(blank=True, choices=[('level', 'Level'), ('view', 'View'), ('incline', 'Incline')], default='level', max_length=255),
        ),
    ]
