# Generated by Django 4.2.7 on 2024-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_listing_slope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description_gr',
            field=models.TextField(blank=True),
        ),
    ]
