# Generated by Django 4.2.7 on 2024-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='building_coefficient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cover_coefficient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
