# Generated by Django 4.2.7 on 2024-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_listing_building_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
