# Generated by Django 4.2.7 on 2024-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_alter_amenities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='heating_system',
            field=models.CharField(blank=True, choices=[('autonomous', 'Autonomous'), ('central', 'Central'), ('air_condition', 'Air Condition'), ('fireplace', 'Fireplace'), ('solar', 'Solar'), ('geothermal', 'Geothermal'), ('other', 'Other'), ('n/a', 'N/A')], default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='power_type',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('natural_gas', 'Natural Gas'), ('heat_pump', 'Heat Pump'), ('other', 'Other'), ('n/a', 'N/A')], default='N/A', max_length=255),
        ),
    ]
