# Generated by Django 4.2.7 on 2024-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_alter_listing_heating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
