# Generated by Django 4.2.7 on 2025-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_alter_listing_county_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='county_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='municipality_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
