# Generated by Django 4.2.7 on 2025-01-04 19:03

from django.db import migrations


def populate_defaults(apps, schema_editor):
    Listing = apps.get_model("listings", "Listing")
    for listing in Listing.objects.all():
        if listing.region_id is None:
            listing.region_id = 0
        if listing.county_id is None:
            listing.county_id = 0
        if listing.municipality_id is None:
            listing.municipality_id = 0
        listing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_alter_listing_county_id_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_defaults),
    ]
