# Generated by Django 4.2.7 on 2025-01-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_auto_20250104_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.owner'),
        ),
    ]
