# Generated by Django 4.2.7 on 2025-01-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_owner_listing_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
