# Generated by Django 4.2.7 on 2025-01-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_owner_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='file',
        ),
        migrations.CreateModel(
            name='OwnerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='owners/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='listings.owner')),
            ],
            options={
                'verbose_name_plural': 'Owner Files',
            },
        ),
    ]
