# Generated by Django 4.2.7 on 2025-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_remove_owner_file_ownerfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='owners/%Y/%m/%d/'),
        ),
    ]
