# Generated by Django 4.2.7 on 2025-02-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_alter_ownerfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='floor_type',
            field=models.CharField(blank=True, choices=[('marble', 'Marble'), ('tile', 'Tile'), ('wooden', 'Wooden'), ('granite', 'Granite'), ('mosaic', 'Mosaic'), ('stone', 'Stone'), ('laminate', 'Laminate'), ('parquet', 'Parquet'), ('carpet', 'Carpet'), ('cement', 'Cement'), ('industrial_floor', 'Industrial Floor'), ('other', 'Other')], default='marble', max_length=255),
        ),
    ]
