# Generated by Django 4.2.7 on 2025-02-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_alter_listing_floor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='county',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='county_gr',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='region',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='region_gr',
        ),
    ]
