# Generated by Django 4.2.7 on 2025-04-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0047_remove_listing_county_remove_listing_county_gr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('description_gr', models.TextField(blank=True)),
                ('address_number', models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=255)),
                ('municipality_id', models.IntegerField(blank=True, null=True)),
                ('county_id', models.IntegerField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[listings.models.validate_zero])),
                ('currency', models.CharField(blank=True, default='€', max_length=255)),
                ('floor_area', models.FloatField(blank=True, null=True, validators=[listings.models.validate_zero])),
                ('bedrooms', models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero])),
                ('wc', models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero])),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('kitchens', models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero])),
                ('bathrooms', models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero])),
                ('living_rooms', models.IntegerField(blank=True, null=True, validators=[listings.models.validate_zero])),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('distance_from_sea', models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero])),
                ('distance_from_city', models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero])),
                ('distance_from_airport', models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero])),
                ('distance_from_village', models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero])),
                ('distance_from_port', models.IntegerField(blank=True, default=0, null=True, validators=[listings.models.validate_zero])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('amenities', models.ManyToManyField(blank=True, related_name='short_term_listings', to='listings.amenities')),
                ('listing_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_term_listings', to='listings.owner')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ShortTermImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_first', models.BooleanField(default=False, null=True)),
                ('order', models.PositiveIntegerField(default=0, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.shorttermlisting')),
            ],
            options={
                'verbose_name_plural': 'Short Term Images',
            },
        ),
    ]
