# Generated by Django 4.2.7 on 2025-04-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_shorttermlisting_shorttermimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorttermlisting',
            old_name='address',
            new_name='address_street',
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='address_street_gr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
