# Generated by Django 4.2.7 on 2025-04-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_rename_address_shorttermlisting_address_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermlisting',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
