# Generated by Django 4.2.7 on 2025-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_shorttermlisting_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermlisting',
            name='municipality_gr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
