# Generated by Django 4.2.7 on 2025-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_shorttermlisting_municipality_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermlisting',
            name='max_adults',
            field=models.PositiveIntegerField(default=1, help_text='Max number of adults'),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='max_children',
            field=models.PositiveIntegerField(default=0, help_text='Max number of children'),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='max_guests',
            field=models.PositiveIntegerField(default=1, help_text='Total max people allowed'),
        ),
    ]
