# Generated by Django 4.2.7 on 2025-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0052_shorttermlisting_max_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermlisting',
            name='availability_end',
            field=models.DateField(blank=True, help_text='End date of availability', null=True),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='availability_start',
            field=models.DateField(blank=True, help_text='Start date of availability', null=True),
        ),
    ]
