# Generated by Django 4.2.7 on 2025-04-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0053_shorttermlisting_availability_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttermlisting',
            name='availability_end',
        ),
        migrations.RemoveField(
            model_name='shorttermlisting',
            name='availability_start',
        ),
    ]
