# Generated by Django 4.2.7 on 2026-01-08 17:29

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0055_alter_listing_construction_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='shorttermlisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[listings.models.validate_zero]),
        ),
    ]
