# Generated by Django 4.2.7 on 2026-01-08 17:40

from decimal import Decimal
from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0056_alter_listing_price_alter_shorttermlisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[listings.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='shorttermlisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[listings.models.validate_zero]),
        ),
    ]
