# Generated by Django 4.2.7 on 2026-01-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0057_alter_listing_price_alter_shorttermlisting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermSeasonalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='listings.shorttermlisting')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
