# Generated by Django 4.2.7 on 2026-01-15 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0058_shorttermseasonalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermlisting',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time cleaning fee in EUR', max_digits=8),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='climate_crisis_fee_per_night',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Climate Crisis Resilience Fee per night in EUR', max_digits=6),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='municipality_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Municipality tax rate percentage (e.g., 1.5 for 1.5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee percentage (if applicable)', max_digits=5),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='VAT rate percentage (e.g., 13 for 13%)', max_digits=5),
        ),
    ]
