# Generated by Django 4.2.7 on 2026-01-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0059_shorttermlisting_cleaning_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', 'Euro (€)'), ('$', 'US Dollar ($)'), ('£', 'British Pound (£)')], default='€', max_length=255),
        ),
        migrations.AlterField(
            model_name='shorttermlisting',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', 'Euro (€)'), ('$', 'US Dollar ($)'), ('£', 'British Pound (£)')], default='€', max_length=255),
        ),
    ]
