# Generated by Django 4.2.7 on 2026-01-15 20:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0060_alter_listing_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermlisting',
            name='municipality_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Municipality tax rate percentage (e.g., 1.25 for 1.25%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shorttermlisting',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee percentage (e.g., 5.50 for 5.5%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shorttermlisting',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='VAT rate percentage (e.g., 13.25 for 13.25%)', max_digits=5),
        ),
    ]
