# Generated by Django 4.2.7 on 2026-01-20 11:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0061_alter_shorttermlisting_municipality_tax_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttermlisting',
            name='service_fee_rate',
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time service/platform fee in EUR', max_digits=8),
        ),
    ]
