# Generated by Django 4.2.7 on 2026-01-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0062_remove_shorttermlisting_service_fee_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermlisting',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Property title/name (e.g., "Cozy Apartment in Athens Center")', max_length=200),
        ),
        migrations.AddField(
            model_name='shorttermlisting',
            name='title_gr',
            field=models.CharField(blank=True, default='', help_text='Τίτλος ακινήτου (π.χ., "Άνετο Διαμέρισμα στο Κέντρο Αθήνας")', max_length=200),
        ),
    ]
