# Generated by Django 4.2.7 on 2026-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0063_shorttermlisting_title_shorttermlisting_title_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shorttermimages',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
