# Generated by Django 4.2.7 on 2026-02-01 10:04

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0064_images_description_shorttermimages_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermListingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload document file', storage=django.core.files.storage.FileSystemStorage(location='media/listing_files'), upload_to='short_term_listing_files/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(choices=[('offer', 'Offer/Proposal'), ('contract', 'Contract'), ('inspection', 'Inspection Report'), ('appraisal', 'Appraisal/Valuation'), ('title_deed', 'Title Deed'), ('energy_certificate', 'Energy Performance Certificate'), ('floor_plan', 'Floor Plan'), ('survey', 'Survey/Topographical Plan'), ('permit', 'Building Permit'), ('tax_document', 'Tax Document'), ('utility_bill', 'Utility Bill'), ('insurance', 'Insurance Document'), ('correspondence', 'Correspondence/Email'), ('note', 'Internal Note'), ('photo_additional', 'Additional Photos'), ('legal', 'Legal Document'), ('financial', 'Financial Statement'), ('municipal_approval', 'Municipal Approval'), ('zoning', 'Zoning Document'), ('environmental', 'Environmental Report'), ('structural', 'Structural Report'), ('mortgage', 'Mortgage Document'), ('lease', 'Lease Agreement'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this file was uploaded')),
                ('listing', models.ForeignKey(help_text='The short-term listing this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='listings.shorttermlisting')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Agent who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_short_term_listing_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Short Term Listing File',
                'verbose_name_plural': 'Short Term Listing Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload document file', storage=django.core.files.storage.FileSystemStorage(location='media/listing_files'), upload_to='listing_files/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(choices=[('offer', 'Offer/Proposal'), ('contract', 'Contract'), ('inspection', 'Inspection Report'), ('appraisal', 'Appraisal/Valuation'), ('title_deed', 'Title Deed'), ('energy_certificate', 'Energy Performance Certificate'), ('floor_plan', 'Floor Plan'), ('survey', 'Survey/Topographical Plan'), ('permit', 'Building Permit'), ('tax_document', 'Tax Document'), ('utility_bill', 'Utility Bill'), ('insurance', 'Insurance Document'), ('correspondence', 'Correspondence/Email'), ('note', 'Internal Note'), ('photo_additional', 'Additional Photos'), ('legal', 'Legal Document'), ('financial', 'Financial Statement'), ('municipal_approval', 'Municipal Approval'), ('zoning', 'Zoning Document'), ('environmental', 'Environmental Report'), ('structural', 'Structural Report'), ('mortgage', 'Mortgage Document'), ('lease', 'Lease Agreement'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this file was uploaded')),
                ('listing', models.ForeignKey(help_text='The listing this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='listings.listing')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Agent who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_listing_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing File',
                'verbose_name_plural': 'Listing Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
