# Generated by Django 4.2.7 on 2026-02-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0065_shorttermlistingfile_listingfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfile',
            name='file',
            field=models.FileField(help_text='Upload document file', upload_to='listing_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='shorttermlistingfile',
            name='file',
            field=models.FileField(help_text='Upload document file', upload_to='short_term_listing_files/%Y/%m/%d/'),
        ),
    ]
