# Generated by Django 4.2.7 on 2025-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_shorttermbooking_admin_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermbooking',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('el', 'Greek')], default='en', max_length=2),
        ),
    ]
