# Generated by Django 4.2.7 on 2025-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_shorttermbooking_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorttermbooking',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='last_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
