# Generated by Django 4.2.7 on 2025-04-16 14:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_name_shorttermbooking_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermbooking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+306998765432', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
