# Generated by Django 4.2.7 on 2025-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_shorttermbooking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermbooking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
