# Generated by Django 4.2.7 on 2025-04-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_shorttermbooking_adults_shorttermbooking_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttermbooking',
            name='confirmed',
        ),
    ]
