# Generated by Django 4.2.7 on 2025-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_shorttermbooking_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttermbooking',
            name='token',
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='reference',
            field=models.CharField(default='QWDSAQWE12', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
