# Generated by Django 4.2.7 on 2025-04-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_shorttermbooking_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorttermbooking',
            old_name='reference',
            new_name='reference_number',
        ),
    ]
