# Generated by Django 4.2.7 on 2025-11-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_reference_shorttermbooking_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermbooking',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
