# Generated by Django 4.2.7 on 2026-01-08 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_shorttermbooking_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermbooking',
            name='total_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
