# Generated by Django 4.2.7 on 2026-01-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_shorttermbooking_total_nights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermBookingNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nights', to='bookings.shorttermbooking')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('booking', 'date')},
            },
        ),
    ]
