# Generated by Django 4.2.7 on 2026-01-14 18:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_shorttermbookingnight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermbooking',
            name='climate_crisis_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Climate Crisis Resilience Fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='municipality_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Municipality accommodation tax', max_digits=10),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base accommodation cost before taxes', max_digits=10),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='13% VAT', max_digits=10),
        ),
    ]
