# Generated by Django 4.2.7 on 2026-01-15 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_shorttermbooking_climate_crisis_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermbooking',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time cleaning fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform/service fee', max_digits=10),
        ),
    ]
