# Generated by Django 4.2.7 on 2026-01-15 20:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_shorttermbooking_cleaning_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermbooking',
            name='municipality_tax',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Municipality accommodation tax', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shorttermbooking',
            name='vat',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='13% VAT', max_digits=10),
        ),
    ]
