# Generated by Django 4.2.7 on 2026-01-18 13:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0015_alter_shorttermbooking_municipality_tax_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorttermbooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Short-Term Booking', 'verbose_name_plural': 'Short-Term Bookings'},
        ),
        migrations.AlterModelOptions(
            name='shorttermbookingnight',
            options={'ordering': ['date'], 'verbose_name': 'Booking Night', 'verbose_name_plural': 'Booking Nights'},
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount in currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='discount_applied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when discount was applied', null=True),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='discount_applied_by',
            field=models.ForeignKey(blank=True, help_text='Admin who applied the discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Optional reason for discount', max_length=255),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], help_text='Type of discount: percentage or fixed amount', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Discount value (e.g., 10 for 10% or 50 for €50)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shorttermbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shorttermbooking',
            name='admin_confirmed',
            field=models.BooleanField(default=False, help_text="Legacy field - use 'status' instead"),
        ),
        migrations.AlterField(
            model_name='shorttermbooking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base accommodation cost before discount and taxes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shorttermbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including discount and all taxes/fees', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shorttermbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shorttermbooking',
            name='vat',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='VAT (calculated on discounted subtotal)', max_digits=10),
        ),
    ]
